server:
  port: 8081
  servlet:
    context-path: /tender

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5433/tender-db
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  #     driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false



  # JPA and Hibernate #####
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: create-drop
        show_sql: true
        format_sql: true


  output:
    ansi:
      enabled: detect

#
logging:
  level:
    org.hibernate: info
    org.springframework.web: debug




